# Vitest Library Cache Entry
# Generated: 2025-10-12T00:00:00Z
# Updated with correct version information

library_info:
  name: "Vitest"
  version: "3.2.4"
  context7_id: "/vitest-dev/vitest/v3_2_4"
  trust_score: 8.3
  snippet_count: 1183
  last_updated: "2025-10-12T00:00:00Z"
  last_checked: "2025-10-12T00:00:00Z"
  topics: ["testing", "mocking", "coverage", "configuration"]
  
cache_entry:
  file_path: "libraries/vitest/docs.md"
  size_bytes: 28145
  hit_count: 1
  last_accessed: "2025-10-12T00:00:00Z"
  
refresh_policy:
  max_age_days: 14
  auto_refresh: true
  library_type: "active"
  
documentation_summary:
  version: "3.2.4"
  topics_covered:
    - "Test framework setup and configuration"
    - "Mocking capabilities (MSW, vi.mock, vi.spyOn)"
    - "Coverage reporting (v8, istanbul, custom providers)"
    - "TypeScript integration"
    - "Component testing"
    - "Environment variable mocking (vi.stubEnv)"
  
  key_concepts:
    - "Test configuration with defineConfig"
    - "Mock functions and module mocking"
    - "Coverage providers and reporters"
    - "Coverage thresholds and watermarks"
    - "TypeScript native support"
    - "Async testing with vi.setConfig"
    - "MSW integration for API mocking"
  
  version_specific_features:
    - "Enhanced coverage threshold API"
    - "Improved mock service worker integration"
    - "Better TypeScript coverage support"
    - "Custom coverage reporters support"
    - "Glob pattern coverage thresholds"
