# Elasticsearch configuration for HA Ingestor

cluster.name: homeiq-cluster
node.name: homeiq-node

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings
discovery.type: single-node

# Security settings (disabled for development)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false

# Monitoring settings
xpack.monitoring.collection.enabled: true

# Index settings
action.auto_create_index: true
index.number_of_shards: 1
index.number_of_replicas: 0

# Logging settings
logger.level: INFO
logger.org.elasticsearch.discovery: DEBUG

# Memory settings
bootstrap.memory_lock: false

# Path settings
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Performance settings
indices.memory.index_buffer_size: 20%
indices.queries.cache.size: 10%

# Log retention settings
action.destructive_requires_name: true
