version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: ha-ingestor-influxdb-dev
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-admin123}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
    volumes:
      - influxdb_data_dev:/var/lib/influxdb2
      - influxdb_config_dev:/etc/influxdb2
    networks:
      - ha-ingestor-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  websocket-ingestion:
    build:
      context: ./services/websocket-ingestion
      dockerfile: Dockerfile.dev
    container_name: ha-ingestor-websocket-dev
    restart: unless-stopped
    environment:
      - HOME_ASSISTANT_URL=${HOME_ASSISTANT_URL}
      - HOME_ASSISTANT_TOKEN=${HOME_ASSISTANT_TOKEN}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - LOG_LEVEL=DEBUG
    volumes:
      - ./services/websocket-ingestion:/app
      - /app/__pycache__
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  enrichment-pipeline:
    build:
      context: .
      dockerfile: services/enrichment-pipeline/Dockerfile.dev
    container_name: ha-ingestor-enrichment-dev
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - LOG_LEVEL=DEBUG
    volumes:
      - ./services/enrichment-pipeline:/app
      - /app/__pycache__
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  weather-api:
    build:
      context: ./services/weather-api
      dockerfile: Dockerfile.dev
    container_name: ha-ingestor-weather-dev
    restart: unless-stopped
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_API_URL=${WEATHER_API_URL:-https://api.openweathermap.org/data/2.5}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - LOG_LEVEL=DEBUG
    volumes:
      - ./services/weather-api:/app
      - /app/__pycache__
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  admin-api:
    build:
      context: ./services/admin-api
      dockerfile: Dockerfile.dev
    container_name: ha-ingestor-admin-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=DEBUG
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - ENABLE_AUTH=false
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-super-secret-jwt-key}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-adminpass}
      - WEBSOCKET_INGESTION_URL=http://websocket-ingestion:8001
      - ENRICHMENT_PIPELINE_URL=http://enrichment-pipeline:8002
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
    volumes:
      - ./services/admin-api:/app
      - /app/__pycache__
    depends_on:
      influxdb:
        condition: service_healthy
      websocket-ingestion:
        condition: service_healthy
      enrichment-pipeline:
        condition: service_healthy
    networks:
      - ha-ingestor-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  data-retention:
    build:
      context: ./services/data-retention
      dockerfile: Dockerfile.dev
    container_name: ha-ingestor-data-retention-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - LOG_LEVEL=DEBUG
      - CLEANUP_INTERVAL_HOURS=${CLEANUP_INTERVAL_HOURS:-24}
      - MONITORING_INTERVAL_MINUTES=${MONITORING_INTERVAL_MINUTES:-5}
      - COMPRESSION_INTERVAL_HOURS=${COMPRESSION_INTERVAL_HOURS:-24}
      - BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS:-24}
      - BACKUP_DIR=${BACKUP_DIR:-/backups}
    volumes:
      - ./services/data-retention:/app
      - /app/__pycache__
      - data_retention_backups_dev:/backups
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  health-dashboard:
    build:
      context: ./services/health-dashboard
      dockerfile: Dockerfile.dev
    container_name: ha-ingestor-dashboard-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    volumes:
      - ./services/health-dashboard:/app
      - /app/node_modules
    depends_on:
      admin-api:
        condition: service_healthy
    networks:
      - ha-ingestor-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  influxdb_data_dev:
  influxdb_config_dev:
  data_retention_backups_dev:

networks:
  ha-ingestor-network-dev:
    driver: bridge
