name: ha-ingestor

services:
  influxdb:
    image: influxdb:2.7
    container_name: ha-ingestor-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-admin123}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  websocket-ingestion:
    build:
      context: .
      dockerfile: services/websocket-ingestion/Dockerfile
    container_name: ha-ingestor-websocket
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - infrastructure/.env.websocket
      - infrastructure/.env.weather
      - infrastructure/.env.influxdb
    environment:
      - HOME_ASSISTANT_URL=${HOME_ASSISTANT_URL:-}
      - HOME_ASSISTANT_TOKEN=${HOME_ASSISTANT_TOKEN:-}
      - ENRICHMENT_SERVICE_URL=http://enrichment-pipeline:8002
      - WEBSOCKET_INGESTION_PORT=8001
      - ENABLE_HOME_ASSISTANT=true
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/app/logs}
      - LOG_FORMAT=json
      - LOG_OUTPUT=both
      # Weather API Configuration
      - WEATHER_API_KEY=${WEATHER_API_KEY:-}
      - WEATHER_API_URL=${WEATHER_API_URL:-https://api.openweathermap.org/data/2.5}
      - WEATHER_DEFAULT_LOCATION=${WEATHER_DEFAULT_LOCATION:-Las Vegas,NV,US}
      - WEATHER_ENRICHMENT_ENABLED=${WEATHER_ENRICHMENT_ENABLED:-true}
      - WEATHER_CACHE_MINUTES=${WEATHER_CACHE_MINUTES:-15}
      - WEATHER_RATE_LIMIT_PER_MINUTE=${WEATHER_RATE_LIMIT_PER_MINUTE:-50}
      - WEATHER_RATE_LIMIT_PER_DAY=${WEATHER_RATE_LIMIT_PER_DAY:-900}
      - WEATHER_REQUEST_TIMEOUT=${WEATHER_REQUEST_TIMEOUT:-10}
    volumes:
      - ha_ingestor_logs:/var/log/ha-ingestor
    depends_on:
      enrichment-pipeline:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
        labels: "service=websocket-ingestion"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  enrichment-pipeline:
    build:
      context: .
      dockerfile: services/enrichment-pipeline/Dockerfile
    container_name: ha-ingestor-enrichment
    restart: unless-stopped
    ports:
      - "8002:8002"
    env_file:
      - infrastructure/.env.influxdb
      - infrastructure/.env.weather
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/app/logs}
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  admin-api:
    build:
      context: .
      dockerfile: services/admin-api/Dockerfile
    container_name: ha-ingestor-admin
    restart: unless-stopped
    ports:
      - "8003:8004"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/app/logs}
      - API_HOST=0.0.0.0
      - API_PORT=8004
      - ENABLE_AUTH=false
      - WEATHER_API_KEY=${WEATHER_API_KEY:-}
      - HOME_ASSISTANT_URL=${HOME_ASSISTANT_URL:-}
      - HOME_ASSISTANT_TOKEN=${HOME_ASSISTANT_TOKEN:-}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-super-secret-jwt-key}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-adminpass}
      - WEBSOCKET_INGESTION_URL=http://websocket-ingestion:8001
      - ENRICHMENT_PIPELINE_URL=http://enrichment-pipeline:8002
    volumes:
      - ./infrastructure:/app/infrastructure:rw
      - ./docker-compose.yml:/app/docker-compose.yml:ro
    depends_on:
      influxdb:
        condition: service_healthy
      websocket-ingestion:
        condition: service_healthy
      enrichment-pipeline:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  data-retention:
    build:
      context: .
      dockerfile: services/data-retention/Dockerfile
    container_name: ha-ingestor-data-retention
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/app/logs}
      - CLEANUP_INTERVAL_HOURS=${CLEANUP_INTERVAL_HOURS:-24}
      - MONITORING_INTERVAL_MINUTES=${MONITORING_INTERVAL_MINUTES:-5}
      - COMPRESSION_INTERVAL_HOURS=${COMPRESSION_INTERVAL_HOURS:-24}
      - BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS:-24}
      - BACKUP_DIR=${BACKUP_DIR:-/backups}
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - data_retention_backups:/backups

  carbon-intensity:
    build:
      context: .
      dockerfile: services/carbon-intensity-service/Dockerfile
    container_name: ha-ingestor-carbon-intensity
    restart: unless-stopped
    ports:
      - "8010:8010"
    environment:
      - WATTTIME_API_TOKEN=${WATTTIME_API_TOKEN:-}
      - GRID_REGION=${GRID_REGION:-CAISO_NORTH}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - SERVICE_PORT=8010
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  electricity-pricing:
    build:
      context: .
      dockerfile: services/electricity-pricing-service/Dockerfile
    container_name: ha-ingestor-electricity-pricing
    restart: unless-stopped
    ports:
      - "8011:8011"
    environment:
      - PRICING_PROVIDER=${PRICING_PROVIDER:-awattar}
      - PRICING_API_KEY=${PRICING_API_KEY:-}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - SERVICE_PORT=8011
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8011/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  air-quality:
    build:
      context: .
      dockerfile: services/air-quality-service/Dockerfile
    container_name: ha-ingestor-air-quality
    restart: unless-stopped
    ports:
      - "8012:8012"
    environment:
      - AIRNOW_API_KEY=${AIRNOW_API_KEY:-}
      - LATITUDE=${LATITUDE:-36.1699}
      - LONGITUDE=${LONGITUDE:--115.1398}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - SERVICE_PORT=8012
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8012/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  calendar:
    build:
      context: .
      dockerfile: services/calendar-service/Dockerfile
    container_name: ha-ingestor-calendar
    restart: unless-stopped
    ports:
      - "8013:8013"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN:-}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - SERVICE_PORT=8013
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8013/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  smart-meter:
    build:
      context: .
      dockerfile: services/smart-meter-service/Dockerfile
    container_name: ha-ingestor-smart-meter
    restart: unless-stopped
    ports:
      - "8014:8014"
    environment:
      - METER_TYPE=${METER_TYPE:-generic}
      - METER_API_TOKEN=${METER_API_TOKEN:-}
      - METER_DEVICE_ID=${METER_DEVICE_ID:-}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - SERVICE_PORT=8014
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8014/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  sports-api:
    build:
      context: .
      dockerfile: services/sports-api/Dockerfile.dev
    container_name: ha-sports-api
    restart: unless-stopped
    ports:
      - "8015:8015"
    env_file:
      - infrastructure/env.sports.template
    environment:
      - API_SPORTS_KEY=${API_SPORTS_KEY:-}
      - SPORTS_API_PORT=8015
      - NFL_ENABLED=${NFL_ENABLED:-true}
      - NHL_ENABLED=${NHL_ENABLED:-true}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=sports_data
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8015/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  sports-data:
    build:
      context: ./services/sports-data
      dockerfile: Dockerfile
    container_name: ha-ingestor-sports-data
    restart: unless-stopped
    ports:
      - "8005:8005"
    environment:
      - SPORTS_API_KEY=${SPORTS_API_KEY:-}
      - SPORTS_API_PROVIDER=${SPORTS_API_PROVIDER:-espn}
      - PORT=8005
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8005/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  health-dashboard:
    build:
      context: ./services/health-dashboard
      dockerfile: Dockerfile
    container_name: ha-ingestor-dashboard
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8003/api/v1
      - VITE_WS_URL=ws://localhost:8001/ws
      - VITE_ENVIRONMENT=production
    depends_on:
      admin-api:
        condition: service_healthy
      sports-data:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  influxdb_data:
  influxdb_config:
  data_retention_backups:
  ha_ingestor_logs:

networks:
  ha-ingestor-network:
    driver: bridge
