name: ha-ingestor

services:
  influxdb:
    image: influxdb:2.7
    container_name: ha-ingestor-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-admin123}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  websocket-ingestion:
    build:
      context: .
      dockerfile: services/websocket-ingestion/Dockerfile
    container_name: ha-ingestor-websocket
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - HOME_ASSISTANT_URL=${HOME_ASSISTANT_URL:-}
      - HOME_ASSISTANT_TOKEN=${HOME_ASSISTANT_TOKEN:-}
      - ENRICHMENT_SERVICE_URL=http://enrichment-pipeline:8002
      - WEBSOCKET_INGESTION_PORT=8001
      - ENABLE_HOME_ASSISTANT=true
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/app/logs}
      - LOG_FORMAT=json
      - LOG_OUTPUT=both
      # Weather API Configuration
      - WEATHER_API_KEY=${WEATHER_API_KEY:-}
      - WEATHER_API_URL=${WEATHER_API_URL:-https://api.openweathermap.org/data/2.5}
      - WEATHER_DEFAULT_LOCATION=${WEATHER_DEFAULT_LOCATION:-Las Vegas,NV,US}
      - WEATHER_ENRICHMENT_ENABLED=${WEATHER_ENRICHMENT_ENABLED:-true}
      - WEATHER_CACHE_MINUTES=${WEATHER_CACHE_MINUTES:-15}
      - WEATHER_RATE_LIMIT_PER_MINUTE=${WEATHER_RATE_LIMIT_PER_MINUTE:-50}
      - WEATHER_RATE_LIMIT_PER_DAY=${WEATHER_RATE_LIMIT_PER_DAY:-900}
      - WEATHER_REQUEST_TIMEOUT=${WEATHER_REQUEST_TIMEOUT:-10}
    volumes:
      - ha_ingestor_logs:/var/log/ha-ingestor
    depends_on:
      enrichment-pipeline:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
        labels: "service=websocket-ingestion"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  enrichment-pipeline:
    build:
      context: .
      dockerfile: services/enrichment-pipeline/Dockerfile
    container_name: ha-ingestor-enrichment
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/app/logs}
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  admin-api:
    build:
      context: .
      dockerfile: services/admin-api/Dockerfile
    container_name: ha-ingestor-admin
    restart: unless-stopped
    ports:
      - "8003:8004"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/app/logs}
      - API_HOST=0.0.0.0
      - API_PORT=8004
      - ENABLE_AUTH=false
      - WEATHER_API_KEY=${WEATHER_API_KEY:-}
      - HOME_ASSISTANT_URL=${HOME_ASSISTANT_URL:-}
      - HOME_ASSISTANT_TOKEN=${HOME_ASSISTANT_TOKEN:-}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-super-secret-jwt-key}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-adminpass}
      - WEBSOCKET_INGESTION_URL=http://websocket-ingestion:8001
      - ENRICHMENT_PIPELINE_URL=http://enrichment-pipeline:8002
    depends_on:
      influxdb:
        condition: service_healthy
      websocket-ingestion:
        condition: service_healthy
      enrichment-pipeline:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  data-retention:
    build:
      context: .
      dockerfile: services/data-retention/Dockerfile
    container_name: ha-ingestor-data-retention
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-ha-ingestor-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-ha-ingestor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-home_assistant_events}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/app/logs}
      - CLEANUP_INTERVAL_HOURS=${CLEANUP_INTERVAL_HOURS:-24}
      - MONITORING_INTERVAL_MINUTES=${MONITORING_INTERVAL_MINUTES:-5}
      - COMPRESSION_INTERVAL_HOURS=${COMPRESSION_INTERVAL_HOURS:-24}
      - BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS:-24}
      - BACKUP_DIR=${BACKUP_DIR:-/backups}
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - data_retention_backups:/backups

  health-dashboard:
    build:
      context: ./services/health-dashboard
      dockerfile: Dockerfile
    container_name: ha-ingestor-dashboard
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8003/api/v1
      - VITE_WS_URL=ws://localhost:8001/ws
      - VITE_ENVIRONMENT=production
    depends_on:
      admin-api:
        condition: service_healthy
    networks:
      - ha-ingestor-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  influxdb_data:
  influxdb_config:
  data_retention_backups:
  ha_ingestor_logs:

networks:
  ha-ingestor-network:
    driver: bridge
