# Ultra-simple Docker Compose - minimal services, no complexity
name: ha-ingestor-simple

services:
  # Database only
  influxdb:
    image: influxdb:2.7
    container_name: ha-ingestor-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=ha-ingestor
      - DOCKER_INFLUXDB_INIT_BUCKET=home_assistant_events
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ha-ingestor-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Single combined service - dashboard + admin API
  app:
    build:
      context: .
      dockerfile: services/health-dashboard/Dockerfile.simple
    container_name: ha-ingestor-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=ha-ingestor-token
      - INFLUXDB_ORG=ha-ingestor
      - INFLUXDB_BUCKET=home_assistant_events
      - LOG_LEVEL=INFO
      - API_HOST=0.0.0.0
      - API_PORT=8003
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  influxdb_data: