version: '3.8'

services:
  ha-ingestor:
    build: .
    container_name: ha-ingestor
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Home Assistant MQTT settings
      - HA_MQTT_HOST=mqtt-broker
      - HA_MQTT_PORT=1883
      - HA_MQTT_CLIENT_ID=ha-ingestor-production
      - HA_MQTT_USERNAME=${HA_MQTT_USERNAME}
      - HA_MQTT_PASSWORD=${HA_MQTT_PASSWORD}

      # Home Assistant WebSocket settings (Production)
      - HA_WS_URL=${HA_WS_URL}
      - HA_WS_TOKEN=${HA_WS_TOKEN}

      # InfluxDB settings
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}

      # Service settings
      - LOG_LEVEL=INFO
      - HEALTH_CHECK_PORT=8000
      - METRICS_ENABLED=true

    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - mqtt-broker
      - influxdb
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

volumes:
  influxdb_data:
