/**
 * TagBadge Component
 * 
 * Reusable badge component for displaying automation tags.
 * Features:
 * - Color-coded by tag type
 * - Hover tooltip with tag explanation
 * - Smooth animations
 * - Accessibility support
 * - Respects prefers-reduced-motion
 */

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface TagBadgeProps {
  tag: string;
  darkMode?: boolean;
  showTooltip?: boolean;
  onClick?: () => void;
}

// Tag color mapping
const TAG_COLORS: Record<string, { bg: string; border: string; text: string }> = {
  'ai-generated': { bg: 'rgba(168, 85, 247, 0.2)', border: 'rgba(168, 85, 247, 0.5)', text: '#c084fc' },
  'energy': { bg: 'rgba(16, 185, 129, 0.2)', border: 'rgba(16, 185, 129, 0.5)', text: '#6ee7b7' },
  'security': { bg: 'rgba(239, 68, 68, 0.2)', border: 'rgba(239, 68, 68, 0.5)', text: '#fca5a5' },
  'comfort': { bg: 'rgba(59, 130, 246, 0.2)', border: 'rgba(59, 130, 246, 0.5)', text: '#93c5fd' },
  'convenience': { bg: 'rgba(168, 85, 247, 0.2)', border: 'rgba(168, 85, 247, 0.5)', text: '#c084fc' },
  'lighting': { bg: 'rgba(245, 158, 11, 0.2)', border: 'rgba(245, 158, 11, 0.5)', text: '#fbbf24' },
  'climate': { bg: 'rgba(6, 182, 212, 0.2)', border: 'rgba(6, 182, 212, 0.5)', text: '#67e8f9' },
  'presence': { bg: 'rgba(249, 115, 22, 0.2)', border: 'rgba(249, 115, 22, 0.5)', text: '#fb923c' },
  'notification': { bg: 'rgba(59, 130, 246, 0.2)', border: 'rgba(59, 130, 246, 0.5)', text: '#93c5fd' },
  'media': { bg: 'rgba(236, 72, 153, 0.2)', border: 'rgba(236, 72, 153, 0.5)', text: '#f9a8d4' },
  'default': { bg: 'rgba(107, 114, 128, 0.2)', border: 'rgba(107, 114, 128, 0.5)', text: '#9ca3af' }
};

// Tag explanations for tooltips
const TAG_EXPLANATIONS: Record<string, string> = {
  'ai-generated': 'Generated by AI automation service',
  'energy': 'Optimizes energy consumption and costs',
  'security': 'Enhances home security and safety',
  'comfort': 'Improves comfort and convenience',
  'convenience': 'Adds convenience and ease of use',
  'lighting': 'Controls lighting and ambiance',
  'climate': 'Manages temperature and climate',
  'presence': 'Responds to presence and occupancy',
  'notification': 'Sends notifications and alerts',
  'media': 'Controls media and entertainment'
};

export const TagBadge: React.FC<TagBadgeProps> = ({
  tag,
  darkMode = false,
  showTooltip = true,
  onClick
}) => {
  const [isHovered, setIsHovered] = useState(false);
  const [prefersReducedMotion, setPrefersReducedMotion] = useState(false);

  // Check for reduced motion preference
  React.useEffect(() => {
    const mediaQuery = window.matchMedia('(prefers-reduced-motion: reduce)');
    setPrefersReducedMotion(mediaQuery.matches);
    
    const handleChange = (e: MediaQueryListEvent) => {
      setPrefersReducedMotion(e.matches);
    };
    
    mediaQuery.addEventListener('change', handleChange);
    return () => mediaQuery.removeEventListener('change', handleChange);
  }, []);

  const colors = TAG_COLORS[tag] || TAG_COLORS.default;
  const explanation = TAG_EXPLANATIONS[tag] || tag;

  const badgeVariants = {
    initial: { scale: 1, opacity: 1 },
    hover: prefersReducedMotion ? {} : { scale: 1.05 },
    tap: prefersReducedMotion ? {} : { scale: 0.95 }
  };

  const tooltipVariants = {
    hidden: { opacity: 0, y: -5, scale: 0.95 },
    visible: prefersReducedMotion ? { opacity: 1, y: 0, scale: 1 } : {
      opacity: 1,
      y: 0,
      scale: 1,
      transition: {
        type: 'spring',
        stiffness: 300,
        damping: 20
      }
    }
  };

  return (
    <div className="relative inline-block">
      {/* Main Badge */}
      <motion.div
        className={`flex items-center gap-1 px-2 py-0.5 rounded-xl text-xs font-medium transition-all backdrop-blur-sm ${onClick ? 'cursor-pointer' : ''}`}
        style={{
          background: colors.bg,
          border: `1px solid ${colors.border}`,
          color: colors.text
        }}
        variants={badgeVariants}
        initial="initial"
        whileHover="hover"
        whileTap={onClick ? "tap" : undefined}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
        onClick={onClick}
        role={onClick ? 'button' : undefined}
        aria-label={`Tag: ${tag}${showTooltip ? `. ${explanation}` : ''}`}
      >
        <span>{tag}</span>
      </motion.div>

      {/* Tooltip */}
      {showTooltip && (
        <AnimatePresence>
          {isHovered && (
            <motion.div
              className="absolute bottom-full left-1/2 mb-2 z-50 px-3 py-2 rounded-xl text-xs whitespace-nowrap pointer-events-none backdrop-blur-sm"
              style={{
                background: darkMode ? 'rgba(30, 41, 59, 0.95)' : 'rgba(255, 255, 255, 0.95)',
                border: darkMode ? '1px solid rgba(51, 65, 85, 0.8)' : '1px solid rgba(203, 213, 225, 0.8)',
                color: darkMode ? '#cbd5e1' : '#1e293b',
                transform: 'translateX(-50%)',
                boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.3)'
              }}
              variants={tooltipVariants}
              initial="hidden"
              animate="visible"
              exit="hidden"
            >
              {explanation}
              {/* Tooltip arrow */}
              <div
                className="absolute top-full left-1/2 -mt-1"
                style={{
                  width: 0,
                  height: 0,
                  borderLeft: '4px solid transparent',
                  borderRight: '4px solid transparent',
                  borderTop: `4px solid ${darkMode ? 'rgba(30, 41, 59, 0.95)' : 'rgba(255, 255, 255, 0.95)'}`,
                  transform: 'translateX(-50%)'
                }}
              />
            </motion.div>
          )}
        </AnimatePresence>
      )}
    </div>
  );
};

