/**
 * Proactive Suggestions Page
 * Epic AI-21: Context-aware automation suggestions from weather, sports, energy
 * 
 * Displays suggestions generated by proactive-agent-service (Port 8031)
 * that analyzes external data sources to create intelligent automation ideas.
 */

import React, { useEffect, useState, useCallback } from 'react';
import { AnimatePresence } from 'framer-motion';
import toast from 'react-hot-toast';
import { useAppStore } from '../store';
import { proactiveApi, ProactiveAPIError } from '../services/proactiveApi';
import { ProactiveSuggestionCard, ProactiveStats, ProactiveFilters } from '../components/proactive';
import { LoadingSpinner } from '../components/LoadingSpinner';
import type {
  ProactiveSuggestion,
  ProactiveSuggestionFilters,
  ProactiveSuggestionStats,
} from '../types/proactive';

export const ProactiveSuggestions: React.FC = () => {
  const { darkMode } = useAppStore();

  // State
  const [suggestions, setSuggestions] = useState<ProactiveSuggestion[]>([]);
  const [stats, setStats] = useState<ProactiveSuggestionStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [statsLoading, setStatsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [triggerLoading, setTriggerLoading] = useState(false);
  const [filters, setFilters] = useState<ProactiveSuggestionFilters>({
    context_type: null,
    status: null,
    limit: 50,
    offset: 0,
  });

  // Load suggestions
  const loadSuggestions = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await proactiveApi.getSuggestions(filters);
      setSuggestions(response.suggestions);
    } catch (err) {
      const message = err instanceof ProactiveAPIError 
        ? err.message 
        : 'Failed to load suggestions';
      setError(message);
      console.error('Failed to load proactive suggestions:', err);
    } finally {
      setLoading(false);
    }
  }, [filters]);

  // Load stats
  const loadStats = useCallback(async () => {
    setStatsLoading(true);

    try {
      const statsData = await proactiveApi.getStats();
      setStats(statsData);
    } catch (err) {
      console.error('Failed to load stats:', err);
      // Don't show error for stats, just log it
    } finally {
      setStatsLoading(false);
    }
  }, []);

  // Initial load
  useEffect(() => {
    loadSuggestions();
    loadStats();
  }, [loadSuggestions, loadStats]);

  // Handle filter change
  const handleFilterChange = (newFilters: ProactiveSuggestionFilters) => {
    setFilters(newFilters);
  };

  // Handle approve
  const handleApprove = async (id: string) => {
    await proactiveApi.updateSuggestionStatus(id, 'approved');
    setSuggestions(prev => 
      prev.map(s => s.id === id ? { ...s, status: 'approved' } : s)
    );
    await loadStats(); // Refresh stats
  };

  // Handle reject
  const handleReject = async (id: string) => {
    await proactiveApi.updateSuggestionStatus(id, 'rejected');
    setSuggestions(prev => 
      prev.map(s => s.id === id ? { ...s, status: 'rejected' } : s)
    );
    await loadStats(); // Refresh stats
  };

  // Handle delete
  const handleDelete = async (id: string) => {
    await proactiveApi.deleteSuggestion(id);
    setSuggestions(prev => prev.filter(s => s.id !== id));
    await loadStats(); // Refresh stats
  };

  // Handle manual trigger
  const handleTrigger = async () => {
    setTriggerLoading(true);
    try {
      const result = await proactiveApi.triggerGeneration();
      if (result.success) {
        toast.success('Suggestion generation triggered!');
        // Reload after a short delay to allow generation to complete
        setTimeout(() => {
          loadSuggestions();
          loadStats();
        }, 2000);
      } else {
        toast.error('Trigger completed but no new suggestions generated');
      }
    } catch (err) {
      const message = err instanceof ProactiveAPIError 
        ? err.message 
        : 'Failed to trigger generation';
      toast.error(message);
    } finally {
      setTriggerLoading(false);
    }
  };

  // Handle refresh
  const handleRefresh = () => {
    loadSuggestions();
    loadStats();
    toast.success('Refreshed');
  };

  return (
    <div className={`min-h-screen ${darkMode ? 'bg-slate-900' : 'bg-gray-50'}`}>
      <div className="max-w-5xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-6">
          <div className="flex items-center justify-between mb-2">
            <h1 className={`text-2xl font-bold flex items-center gap-3 ${
              darkMode ? 'text-white' : 'text-gray-900'
            }`}>
              <span className="text-3xl">💡</span>
              Proactive Suggestions
            </h1>

            <div className="flex items-center gap-2">
              <button
                onClick={handleTrigger}
                disabled={triggerLoading}
                className={`
                  px-4 py-2 rounded-lg text-sm font-medium transition-all
                  ${triggerLoading 
                    ? 'bg-sky-600 text-white cursor-wait' 
                    : 'bg-sky-500 text-white hover:bg-sky-600'
                  }
                  disabled:opacity-50
                `}
              >
                {triggerLoading ? 'Generating...' : '⚡ Generate'}
              </button>
              <button
                onClick={handleRefresh}
                className={`
                  px-4 py-2 rounded-lg text-sm font-medium transition-colors
                  ${darkMode 
                    ? 'bg-slate-700 text-slate-200 hover:bg-slate-600' 
                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                  }
                `}
              >
                🔄 Refresh
              </button>
            </div>
          </div>

          <p className={`text-sm ${darkMode ? 'text-slate-400' : 'text-gray-500'}`}>
            Context-aware automation ideas from weather, sports events, and energy prices.
            Generated daily at 3 AM.
          </p>
        </div>

        {/* Stats Row */}
        <div className={`
          p-4 rounded-xl mb-6
          ${darkMode ? 'bg-slate-800/50' : 'bg-white border border-gray-200'}
        `}>
          <ProactiveStats stats={stats} loading={statsLoading} darkMode={darkMode} />
        </div>

        {/* Filters Row */}
        <div className={`
          p-4 rounded-xl mb-6
          ${darkMode ? 'bg-slate-800/50' : 'bg-white border border-gray-200'}
        `}>
          <ProactiveFilters 
            filters={filters} 
            onFilterChange={handleFilterChange} 
            darkMode={darkMode} 
          />
        </div>

        {/* Content Area */}
        {loading ? (
          <div className="flex justify-center items-center py-20">
            <LoadingSpinner size="lg" />
          </div>
        ) : error ? (
          <div className={`
            text-center py-20 rounded-xl
            ${darkMode ? 'bg-slate-800/50' : 'bg-white border border-gray-200'}
          `}>
            <div className="text-5xl mb-4">⚠️</div>
            <h3 className={`text-lg font-medium mb-2 ${
              darkMode ? 'text-white' : 'text-gray-900'
            }`}>
              Unable to Load Proactive Suggestions
            </h3>
            <p className={`text-sm mb-4 ${
              darkMode ? 'text-slate-400' : 'text-gray-500'
            }`}>
              {error}
            </p>
            <button
              onClick={handleRefresh}
              className="px-4 py-2 bg-sky-500 text-white rounded-lg hover:bg-sky-600 transition-colors"
            >
              Try Again
            </button>
          </div>
        ) : suggestions.length === 0 ? (
          <div className={`
            text-center py-20 rounded-xl
            ${darkMode ? 'bg-slate-800/50' : 'bg-white border border-gray-200'}
          `}>
            <div className="text-5xl mb-4">🤖</div>
            <h3 className={`text-lg font-medium mb-2 ${
              darkMode ? 'text-white' : 'text-gray-900'
            }`}>
              No Proactive Suggestions Yet
            </h3>
            <p className={`text-sm mb-4 max-w-md mx-auto ${
              darkMode ? 'text-slate-400' : 'text-gray-500'
            }`}>
              The AI analyzes weather, sports, and energy data at 3 AM daily 
              to suggest context-aware automations.
            </p>
            <button
              onClick={handleTrigger}
              disabled={triggerLoading}
              className="px-4 py-2 bg-sky-500 text-white rounded-lg hover:bg-sky-600 transition-colors disabled:opacity-50"
            >
              {triggerLoading ? 'Generating...' : 'Generate Sample Suggestion'}
            </button>
            <p className={`text-xs mt-6 ${darkMode ? 'text-slate-500' : 'text-gray-400'}`}>
              💡 How it works: The AI looks at tomorrow's weather, upcoming sports games, 
              and energy prices to suggest automations that save energy or enhance comfort.
            </p>
          </div>
        ) : (
          <AnimatePresence mode="popLayout">
            {suggestions.map((suggestion) => (
              <ProactiveSuggestionCard
                key={suggestion.id}
                suggestion={suggestion}
                onApprove={handleApprove}
                onReject={handleReject}
                onDelete={handleDelete}
                darkMode={darkMode}
              />
            ))}
          </AnimatePresence>
        )}
      </div>
    </div>
  );
};

export default ProactiveSuggestions;
