"""
Tests for main.py (src.main).

Generated by TappsCodingAgents; import fixed to use project path_setup.
For full main.py coverage, see test_main_service.py.
"""

import pytest

from tests.path_setup import add_service_src

add_service_src(__file__)


def test_main_module_importable():
    """Ensure src.main can be imported after path_setup."""
    from src import main

    assert main is not None
    assert hasattr(main, "WebSocketIngestionService")