"""Add domain column and fix superseded_by FK constraint.

Revision ID: 003_add_domain_and_fix_fk
Revises: 002_fix_memory_type_enum
Create Date: 2026-03-09

Story 41.1: Adds a `domain` column (VARCHAR(30), nullable, indexed) to both
memory.memories and memory.memory_archive for semantic domain classification.

Story 41.5: Drops and re-creates the `superseded_by` FK constraint with
ON DELETE SET NULL to prevent orphaned references when a superseding memory
is deleted.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "003_add_domain_and_fix_fk"
down_revision: str | None = "002_fix_memory_type_enum"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add domain column to memories/archive and fix superseded_by FK."""
    # --- Story 41.1: Add domain column ---

    # Add domain column to memories table
    op.execute(
        "ALTER TABLE memory.memories "
        "ADD COLUMN domain VARCHAR(30)"
    )
    op.execute(
        "CREATE INDEX idx_memories_domain "
        "ON memory.memories (domain)"
    )

    # Add domain column to memory_archive table
    op.execute(
        "ALTER TABLE memory.memory_archive "
        "ADD COLUMN domain VARCHAR(30)"
    )

    # --- Story 41.5: Fix superseded_by FK with ON DELETE SET NULL ---

    # Drop existing FK constraint (name auto-generated by PostgreSQL from 001 migration)
    op.execute(
        "ALTER TABLE memory.memories "
        "DROP CONSTRAINT IF EXISTS memories_superseded_by_fkey"
    )

    # Re-add with ON DELETE SET NULL
    op.execute(
        "ALTER TABLE memory.memories "
        "ADD CONSTRAINT memories_superseded_by_fkey "
        "FOREIGN KEY (superseded_by) REFERENCES memory.memories(id) "
        "ON DELETE SET NULL"
    )


def downgrade() -> None:
    """Remove domain column and revert superseded_by FK."""
    # Revert FK constraint to original (no ON DELETE action)
    op.execute(
        "ALTER TABLE memory.memories "
        "DROP CONSTRAINT IF EXISTS memories_superseded_by_fkey"
    )
    op.execute(
        "ALTER TABLE memory.memories "
        "ADD CONSTRAINT memories_superseded_by_fkey "
        "FOREIGN KEY (superseded_by) REFERENCES memory.memories(id)"
    )

    # Drop domain column from memory_archive
    op.execute(
        "ALTER TABLE memory.memory_archive "
        "DROP COLUMN IF EXISTS domain"
    )

    # Drop domain index and column from memories
    op.execute("DROP INDEX IF EXISTS memory.idx_memories_domain")
    op.execute(
        "ALTER TABLE memory.memories "
        "DROP COLUMN IF EXISTS domain"
    )
