# Playwright Library Cache Entry
# Generated: 2025-10-12T00:00:00Z
# Updated with correct version information

library_info:
  name: "Playwright"
  version: "1.56.0"
  context7_id: "/microsoft/playwright"
  trust_score: 9.9
  snippet_count: 2103
  last_updated: "2025-10-12T00:00:00Z"
  last_checked: "2025-10-12T00:00:00Z"
  topics: ["testing", "automation", "e2e", "assertions", "configuration"]
  
cache_entry:
  file_path: "libraries/playwright/docs.md"
  size_bytes: 45890
  hit_count: 1
  last_accessed: "2025-10-12T00:00:00Z"
  
refresh_policy:
  max_age_days: 14
  auto_refresh: true
  library_type: "active"
  
documentation_summary:
  version: "1.56.0"
  topics_covered:
    - "End-to-end testing configuration"
    - "Browser automation (Chromium, Firefox, WebKit)"
    - "Test configuration and setup"
    - "Assertions and matchers (expect API)"
    - "Cross-browser testing"
    - "Accessibility testing (axe integration)"
  
  key_concepts:
    - "defineConfig for test configuration"
    - "expect assertions with auto-retry"
    - "Test fixtures and Page Object Model"
    - "Parallel execution and workers"
    - "Browser context configuration"
    - "Global setup and teardown"
    - "Soft assertions with expect.soft"
    - "Custom matchers and assertions"
    - "Accessibility testing with AxeBuilder"
  
  version_specific_features:
    - "expect.configure for custom assertion defaults"
    - "expect.set_options for global timeout (Python)"
    - "SetDefaultExpectTimeout for C# tests"
    - "Advanced test configuration with defineConfig"
    - "Integrated web server for development"
    - "Screenshot and snapshot comparison thresholds"
    - "ATTAcomm accessibility testing framework"
