# MongoDB Library Metadata
# Generated: 2025-10-07T16:40:00Z

library:
  name: "mongodb"
  context7_id: "/mongodb/docs"
  version: "6.0.0"
  trust_score: 9
  code_snippets: 800
  description: "MongoDB is a document-oriented NoSQL database used for high volume data storage. It uses JSON-like documents with optional schemas."
  
  topics:
    queries:
      file: "queries.md"
      size: "0KB"
      last_updated: null
      cache_hits: 0
      token_count: 0
      context7_source: "https://docs.mongodb.com/manual/tutorial/query-documents/"
    
    aggregation:
      file: "aggregation.md"
      size: "0KB"
      last_updated: null
      cache_hits: 0
      token_count: 0
      context7_source: "https://docs.mongodb.com/manual/aggregation/"
    
    indexing:
      file: "indexing.md"
      size: "0KB"
      last_updated: null
      cache_hits: 0
      token_count: 0
      context7_source: "https://docs.mongodb.com/manual/indexes/"
  
  cross_references:
    - library: "mongoose"
      topic: "orm"
      relevance: 0.9
    - library: "express"
      topic: "backend"
      relevance: 0.8
    - library: "node.js"
      topic: "runtime"
      relevance: 0.7
    - library: "redis"
      topic: "caching"
      relevance: 0.6
  
  bmad_integration:
    - agent: "architect"
      scenarios: ["database-design", "data-architecture"]
      usage_frequency: 0
    - agent: "dev"
      scenarios: ["database-implementation", "query-optimization"]
      usage_frequency: 0
    - agent: "qa"
      scenarios: ["database-testing", "performance-testing"]
      usage_frequency: 0
  
  performance_metrics:
    total_requests: 0
    cache_hits: 0
    cache_misses: 0
    avg_response_time: "0.00s"
    last_accessed: null
