library: fastapi
context7_id: /fastapi/fastapi
trust_score: null
topics:
- routing
- dependency-injection
- async
total_docs: 0
total_size_bytes: 0
total_tokens: 0
last_updated: null
last_accessed: 2025-12-21T00:42:11.907961+00:00Z
cache_hits: 3
