# pytest Library Cache Entry
# Generated: 2025-10-12T00:00:00Z
# Updated with correct version information

library_info:
  name: "pytest"
  version: "7.4.3+"
  context7_id: "/pytest-dev/pytest"
  trust_score: 9.5
  snippet_count: 614
  last_updated: "2025-10-12T00:00:00Z"
  last_checked: "2025-10-12T00:00:00Z"
  topics: ["testing", "fixtures", "parametrization", "async"]
  
cache_entry:
  file_path: "libraries/pytest/docs.md"
  size_bytes: 52340
  hit_count: 1
  last_accessed: "2025-10-12T00:00:00Z"
  
refresh_policy:
  max_age_days: 30
  auto_refresh: true
  library_type: "stable"
  
documentation_summary:
  version: "7.4.3+"
  topics_covered:
    - "Test framework fundamentals"
    - "Fixture management and scoping"
    - "Test parametrization (pytest.mark.parametrize)"
    - "Assertion patterns and introspection"
    - "Test discovery and execution"
    - "Async fixture handling (deprecated patterns)"
  
  key_concepts:
    - "Test fixtures with dependency injection"
    - "Parametrized tests with pytest.mark.parametrize"
    - "Fixture scopes (function, class, module, session)"
    - "Test discovery conventions"
    - "Assertion introspection and helpers"
    - "Plugin system and pytest hooks"
    - "Combined fixtures for complex testing"
    - "Custom marks and test selection"
  
  version_specific_features:
    - "pytest.fixture_request for dynamic parametrization"
    - "pytest.param for marking individual test cases"
    - "Async fixture migration patterns (8.4+ deprecations)"
    - "pytestmark global parametrization"
    - "pytest_generate_tests hook for dynamic tests"
