#!/usr/bin/env python3
"""Project intake `brand` + `tokens` into Impeccable PRODUCT.md / DESIGN.md.

TAP-5600. UI agents and Impeccable skills read PRODUCT.md and DESIGN.md. This
store's voice and colours already live in dna-core intake; inventing a third
brand corpus would drift. These files are stamped bridges — edit intake, then
re-emit.

Layout laws that tokens cannot express (hero budget, card rules, anti-slop)
are stated here as fixed storefront rules so polish sessions do not invent
purple/glass defaults.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PRODUCT = REPO_ROOT / "PRODUCT.md"
DEFAULT_DESIGN = REPO_ROOT / "DESIGN.md"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/design_brief.py — do not edit by hand.\n"
    "     Source of truth: dna-core/intake/<slug>.yaml (`brand` + `tokens`).\n"
    "     Regenerate: python3 scripts/design_brief.py --intake <path>\n"
    "     Or re-stamp via scripts/render_dna_core.py --instance. -->\n"
)

# Storefront laws tokens miss. Fixed for the Hydrogen surface; not per-store fiction.
LAYOUT_LAWS = (
    "One job per section: one purpose, one headline, one short supporting sentence.",
    "Hero budget: brand signal, one headline, one supporting sentence, one CTA group, "
    "one dominant image — nothing else in the first viewport.",
    "No cards in the hero. Cards are allowed only when they wrap a user interaction.",
    "Prefer tight radius (4–8px) and flat surfaces; avoid large pills, multi-layer "
    "shadows, and glass / frosted chrome.",
    "Do not invent purple-on-white, purple-to-indigo gradients, or generic SaaS glow.",
    "Motion is presence and hierarchy, not ornament; prefer 2–3 intentional motions.",
)


class BriefError(ValueError):
    """Intake brand/tokens insufficient to emit a usable brief."""


def _require_str(brand: dict[str, Any], key: str) -> str:
    value = brand.get(key)
    if value is None or not str(value).strip():
        msg = f"brand.{key} is required to emit PRODUCT.md"
        raise BriefError(msg)
    return str(value).strip()


def _voice_line(brand: dict[str, Any]) -> str:
    adjectives = brand.get("voice_adjectives") or []
    if not isinstance(adjectives, list) or not adjectives:
        msg = "brand.voice_adjectives must be a non-empty list"
        raise BriefError(msg)
    cleaned = [str(a).strip() for a in adjectives if str(a).strip()]
    if len(cleaned) < 1:
        msg = "brand.voice_adjectives must list at least one adjective"
        raise BriefError(msg)
    return ", ".join(cleaned)


def _flatten_bans(banned: Any) -> list[str]:
    """Collect phrase bans from company_wide / merch_additional (or a flat list)."""
    if banned is None:
        return []
    if isinstance(banned, list):
        return [str(p).strip() for p in banned if str(p).strip()]
    if not isinstance(banned, dict):
        msg = "brand.banned_phrases must be a list or mapping of lists"
        raise BriefError(msg)
    out: list[str] = []
    for key in ("company_wide", "merch_additional"):
        group = banned.get(key)
        if group is None:
            continue
        if not isinstance(group, list):
            msg = f"brand.banned_phrases.{key} must be a list"
            raise BriefError(msg)
        out.extend(str(p).strip() for p in group if str(p).strip())
    return out


def _bullet_block(items: list[str], empty: str) -> str:
    if not items:
        return empty
    return "\n".join(f"- {item}" for item in items)


def build_product_md(intake: dict[str, Any]) -> str:
    """Return PRODUCT.md body for one store's intake."""
    brand = intake.get("brand")
    if not isinstance(brand, dict):
        msg = "intake `brand` must be a mapping"
        raise BriefError(msg)

    name = _require_str(brand, "brand_name")
    sells = _require_str(brand, "what_we_sell")
    customer = _require_str(brand, "customer")
    register = _require_str(brand, "register")
    voice = _voice_line(brand)
    bans = _flatten_bans(brand.get("banned_phrases"))

    anti = _bullet_block(
        bans,
        "_No banned_phrases listed in intake — still refuse generic AI-slop copy._",
    )
    anti_extra = (
        "\n- Purple / indigo SaaS gradients and glassmorphism (Impeccable anti-defaults)\n"
        "- Hero cards, pill clusters, stat strips, and detached promo badges"
    )

    return (
        f"{GENERATED_BANNER}\n"
        f"# {name}\n\n"
        "## Bridge notice\n\n"
        "This file is a **bridge**, not a brand corpus. Edit "
        "`dna-core/intake/<slug>.yaml` (`brand`) and re-emit. Do not fork voice here.\n\n"
        "## Users\n\n"
        f"{customer}\n\n"
        "## Mode\n\n"
        "Transactional Hydrogen storefront — browse, PDP, cart. Agents polish UI "
        "against this brief and `DESIGN.md`; AgentForge genes do not author chrome.\n\n"
        "## What we sell\n\n"
        f"{sells}\n\n"
        "## Brand voice\n\n"
        f"**Adjectives:** {voice}\n\n"
        f"**Register:** {register}\n\n"
        "## Anti-references\n\n"
        "Do not use these phrases or patterns in storefront copy or chrome:\n\n"
        f"{anti}{anti_extra}\n"
    )


def build_design_md(intake: dict[str, Any]) -> str:
    """Return DESIGN.md body from intake tokens + fixed layout laws."""
    brand = intake.get("brand")
    tokens = intake.get("tokens")
    if not isinstance(brand, dict):
        msg = "intake `brand` must be a mapping"
        raise BriefError(msg)
    if not isinstance(tokens, dict) or not tokens:
        msg = "intake `tokens` must be a non-empty mapping"
        raise BriefError(msg)

    name = _require_str(brand, "brand_name")

    color_keys = (
        "bg_primary",
        "bg_surface",
        "bg_elevated",
        "accent_primary",
        "accent_secondary",
        "text_primary",
        "text_secondary",
        "border",
        "error",
    )
    font_keys = ("font_body", "font_display", "font_mono")

    color_rows = []
    for key in color_keys:
        if tokens.get(key):
            color_rows.append(f"| `{key}` | `{tokens[key]}` |")
    if not color_rows:
        msg = "tokens must include at least one colour key"
        raise BriefError(msg)

    font_rows = []
    for key in font_keys:
        if tokens.get(key):
            font_rows.append(f"| `{key}` | `{tokens[key]}` |")
    if not font_rows:
        msg = "tokens must include at least font_body"
        raise BriefError(msg)

    laws = "\n".join(f"- {law}" for law in LAYOUT_LAWS)

    return (
        f"{GENERATED_BANNER}\n"
        f"# {name} — design system\n\n"
        "## Bridge notice\n\n"
        "Colours and faces come from intake `tokens` (also emitted as "
        "`frontend/brand.tokens.json`). Layout laws below fill gaps tokens cannot "
        "express. **Intake remains source of truth** — do not invent a parallel "
        "palette here.\n\n"
        "## Colors\n\n"
        "| Token | Value |\n"
        "| --- | --- |\n"
        + "\n".join(color_rows)
        + "\n\n"
        "## Typography\n\n"
        "| Token | Value |\n"
        "| --- | --- |\n"
        + "\n".join(font_rows)
        + "\n\n"
        "## Layout laws\n\n"
        f"{laws}\n\n"
        "## Implementation anchors\n\n"
        "- CSS variables / CSS modules: `frontend/app/styles/app.css` and "
        "`frontend/app/lib/brand-tokens.ts` read `frontend/brand.tokens.json`.\n"
        "- Before polishing routes, load this file and `PRODUCT.md` so chrome "
        "matches the store — not a generic template.\n"
    )


def build_briefs(intake: dict[str, Any]) -> dict[str, str]:
    """Return `{\"PRODUCT.md\": text, \"DESIGN.md\": text}` or raise BriefError."""
    return {
        "PRODUCT.md": build_product_md(intake),
        "DESIGN.md": build_design_md(intake),
    }


def main(argv: list[str] | None = None) -> int:
    """Write PRODUCT.md and DESIGN.md for one intake; exit non-zero on refusal."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--intake", type=Path, required=True, help="dna-core/intake/<slug>.yaml")
    parser.add_argument("--product-out", type=Path, default=DEFAULT_PRODUCT)
    parser.add_argument("--design-out", type=Path, default=DEFAULT_DESIGN)
    args = parser.parse_args(argv)

    intake = yaml.safe_load(args.intake.read_text(encoding="utf-8"))
    try:
        briefs = build_briefs(intake)
    except BriefError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    args.product_out.parent.mkdir(parents=True, exist_ok=True)
    args.design_out.parent.mkdir(parents=True, exist_ok=True)
    args.product_out.write_text(briefs["PRODUCT.md"], encoding="utf-8")
    args.design_out.write_text(briefs["DESIGN.md"], encoding="utf-8")
    print(f"wrote {args.product_out}")
    print(f"wrote {args.design_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
