library: pydantic
context7_id: /pydantic/pydantic
library_version: v2  # Pydantic v2 is current as of December 2025
trust_score: null
topics:
- validation
- settings
total_docs: 2
total_size_bytes: 0
total_tokens: 0
last_updated: 2025-12-28T22:48:29.766054+00:00Z  # Refreshed December 2025
last_accessed: 2025-12-24T00:24:49.248335+00:00Z
cache_hits: 47
