library: pydantic
context7_id: /pydantic/pydantic
trust_score: null
topics:
- validation
- settings
total_docs: 0
total_size_bytes: 0
total_tokens: 0
last_updated: null
last_accessed: 2025-12-23T10:08:16.359442+00:00Z
cache_hits: 33
