services:
  device-intelligence-service:
    build: .
    ports:
      - "8021:8019"
    env_file:
      - ../../.env
    environment:
      - DEVICE_INTELLIGENCE_PORT=8019
      - DEVICE_INTELLIGENCE_HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - SQLITE_DATABASE_URL=sqlite:///./data/device_intelligence.db
      - HA_URL=http://192.168.1.86:8123
      - MQTT_BROKER=mqtt://192.168.1.86:1883
      - ZIGBEE2MQTT_BASE_TOPIC=zigbee2mqtt
    volumes:
      - ./data:/app/data
    networks:
      - homeiq_homeiq-network
    depends_on:
      - mosquitto
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8019/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    networks:
      - homeiq_homeiq-network

networks:
  homeiq_homeiq-network:
    external: true
