/**
 * Proactive Suggestions Tests - "What proactive suggestions does the system have?"
 *
 * WHY THIS PAGE EXISTS:
 * The Proactive page (/?source=context) shows context-aware automation
 * suggestions generated by the proactive agent service. Unlike the main Ideas
 * page which shows all suggestions, this view filters to show only suggestions
 * triggered by contextual signals (time of day, weather, presence, etc.).
 * Users come here to see what the AI recommends based on current conditions.
 *
 * WHAT THE USER NEEDS:
 * - See context-driven suggestions that are timely and relevant
 * - Filter or browse through proactive recommendations
 * - Understand why each suggestion was generated (context trigger)
 * - Act on suggestions (approve, refine, dismiss)
 *
 * WHAT OLD TESTS MISSED:
 * - "Filters or stats section" had `expect(typeof hasControls).toBe('boolean')` -- always passes
 * - No verification that proactive-specific content actually loaded
 * - No console error detection
 */

import { test, expect } from '@playwright/test';
import { setupAuthenticatedSession } from '../../../shared/helpers/auth-helpers';
import { waitForLoadingComplete } from '../../../shared/helpers/wait-helpers';

test.describe('Proactive Suggestions - What proactive suggestions does the system have?', () => {
  test.beforeEach(async ({ page }) => {
    await setupAuthenticatedSession(page);
    await page.goto('/?source=context');
    await waitForLoadingComplete(page);
  });

  test('@smoke proactive page loads with content', async ({ page }) => {
    await expect(page.locator('#main-content')).toBeVisible({ timeout: 8000 });
  });

  test('page displays proactive suggestions or an empty state', async ({ page }) => {
    const suggestions = page.locator('[data-testid="suggestion-card"]');
    const emptyState = page.getByText(/no.*suggestions|get started|0 suggestions/i).first();
    const content = page.locator('[data-testid="proactive"], [class*="Proactive"], main').first();

    const hasSuggestions = await suggestions.first().isVisible({ timeout: 5000 }).catch(() => false);
    const hasEmpty = await emptyState.isVisible({ timeout: 2000 }).catch(() => false);
    const hasContent = await content.isVisible({ timeout: 2000 }).catch(() => false);

    expect(hasSuggestions || hasEmpty || hasContent).toBe(true);
  });

  test('page has interactive controls for browsing suggestions', async ({ page }) => {
    const controls = page.locator('input, select, button, [class*="filter"], [class*="stat"]');
    const count = await controls.count();
    // The page should have some interactive elements
    expect(count).toBeGreaterThan(0);
  });

  test('context source parameter is reflected in the URL', async ({ page }) => {
    expect(page.url()).toContain('source=context');
  });

  test('no console errors on the proactive page', async ({ page }) => {
    const consoleErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') {
        consoleErrors.push(msg.text());
      }
    });

    await page.reload();
    await waitForLoadingComplete(page);

    const criticalErrors = consoleErrors.filter(
      (e) =>
        !e.includes('favicon') &&
        !e.includes('sourcemap') &&
        !e.includes('DevTools')
    );
    expect(criticalErrors).toEqual([]);
  });
});
