library_id: /pydantic/pydantic
library_name: Pydantic
cached_topics:
  - v2-settings-validation
cached_files:
  - v2-settings-validation.md
last_updated: 2025-12-03
source_reputation: High
benchmark_score: 97

