alias: "Turn on living room light at sunset"
description: "Simple automation to turn on light when sun sets"
id: "living_room_sunset_light"
trigger:
  - platform: sun
    event: sunset
    offset: "-00:30:00"
action:
  - service: light.turn_on
    target:
      entity_id: light.living_room
    data:
      brightness_pct: 80
