markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
context7:
  enabled: true
  defaultTokenLimit: 3000
  cacheDuration: 3600
  integrationLevel: mandatory
  usage_requirement: "MANDATORY for all technology decisions"
  bypass_forbidden: true
  knowledge_base:
    enabled: true
    location: "docs/kb/context7-cache"
    sharding: true
    indexing: true
    cross_references: true
    max_cache_size: "100MB"
    cleanup_interval: 86400
    hit_rate_threshold: 0.7
    fuzzy_match_threshold: 0.5
    analytics_enabled: true
    refresh:
      enabled: true
      default_max_age_days: 30
      check_on_access: true
      auto_queue: true
      notify_stale: true
      auto_process_on_startup: true
      auto_check_on_first_access: true
      library_types:
        stable:
          max_age_days: 30
          examples: ["react", "pytest", "fastapi", "typescript"]
        active:
          max_age_days: 14
          examples: ["vitest", "playwright", "vite"]
        critical:
          max_age_days: 7
          examples: ["security-libs", "jwt", "oauth"]
  agentLimits:
    architect:
      tokenLimit: 4000
      topics: ["architecture", "design-patterns", "scalability"]
      kb_priority: true
      context7_mandatory: true
      bypass_forbidden: true
    dev:
      tokenLimit: 3000
      topics: ["hooks", "routing", "authentication", "testing"]
      kb_priority: true
      context7_mandatory: true
      bypass_forbidden: true
    qa:
      tokenLimit: 2500
      topics: ["testing", "security", "performance"]
      kb_priority: true
      context7_mandatory: true
      bypass_forbidden: true

# Agent-specific document loading configuration
# These documents are automatically loaded during agent activation for optimal context
agentLoadAlwaysFiles:
  architect:
    - docs/architecture/tech-stack.md
    - docs/architecture/source-tree.md
    - docs/architecture/coding-standards.md
  dev:
    - docs/architecture/tech-stack.md
    - docs/architecture/source-tree.md
    - docs/architecture/coding-standards.md
  pm:
    - docs/architecture/tech-stack.md
    - docs/architecture/source-tree.md
  qa:
    - docs/architecture/tech-stack.md
    - docs/architecture/coding-standards.md
    - docs/architecture/testing-strategy.md
  bmad-master:
    - docs/architecture/tech-stack.md
    - docs/architecture/source-tree.md
    - docs/architecture/coding-standards.md
