# Sentence Transformers Library Cache Entry
# Generated: 2025-10-19T00:00:00Z

library_info:
  name: "Sentence Transformers"
  context7_id: "/ukplab/sentence-transformers"
  trust_score: 7.8
  snippet_count: 535
  last_updated: "2025-10-19T00:00:00Z"
  last_checked: "2025-10-19T00:00:00Z"
  topics: ["embeddings", "semantic search", "similarity", "NLP", "text representation"]
  
cache_entry:
  file_path: "libraries/sentence-transformers/docs.md"
  size_bytes: 7890
  hit_count: 0
  last_accessed: "2025-10-19T00:00:00Z"
  
refresh_policy:
  max_age_days: 14
  auto_refresh: true
  library_type: "active"
  
documentation_summary:
  topics_covered:
    - "Sentence embedding generation"
    - "Semantic search and similarity computation"
    - "Query-document encoding"
    - "Sparse encoders (SPLADE)"
    - "OpenVINO INT8 optimization"
    - "Popular model recommendations"
  
  key_concepts:
    - "Dense vector representations for sentences"
    - "Cosine similarity and dot product"
    - "semantic_search utility function"
    - "Batch encoding and GPU acceleration"
    - "Pattern matching for Home Assistant"
  
  ha_ingestor_relevance:
    - "all-MiniLM-L6-v2 for pattern embedding (Phase 1 MVP)"
    - "20MB model size (INT8 quantized)"
    - "50ms for 1000 embeddings"
    - "85% accuracy for pattern detection"

