# Filebeat configuration for HA Ingestor

filebeat.inputs:
  # Docker container logs
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
    parsers:
      - container:
          stream: all
          format: auto
    exclude_lines: ['^$']
    multiline.pattern: '^\s'
    multiline.negate: false
    multiline.match: after

  # Application logs
  - type: log
    enabled: true
    paths:
      - /var/log/homeiq/*.log
    fields:
      logtype: application
      service: homeiq
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    exclude_lines: ['^$']

  # System logs
  - type: log
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/auth.log
    fields:
      logtype: system
    fields_under_root: true
    exclude_lines: ['^$']

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - drop_event:
      when:
        equals:
          message: ""

# Output configuration
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "homeiq-filebeat-%{+yyyy.MM.dd}"
  template.name: "homeiq-filebeat"
  template.pattern: "homeiq-filebeat-*"
  template.settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0
    index.lifecycle.name: "homeiq-policy"
    index.lifecycle.rollover_alias: "homeiq-filebeat"

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Monitoring configuration
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]

# Setup configuration
setup.template.name: "homeiq-filebeat"
setup.template.pattern: "homeiq-filebeat-*"
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  index.lifecycle.name: "homeiq-policy"
  index.lifecycle.rollover_alias: "homeiq-filebeat"

setup.ilm.enabled: true
setup.ilm.rollover_alias: "homeiq-filebeat"
setup.ilm.pattern: "{now/d}-000001"

# Kibana configuration
setup.kibana:
  host: "kibana:5601"

# Dashboard configuration
setup.dashboards.enabled: true
setup.dashboards.directory: /usr/share/filebeat/kibana

# Index lifecycle management
setup.ilm.enabled: true
setup.ilm.rollover_alias: "homeiq-filebeat"
setup.ilm.pattern: "{now/d}-000001"
